alias: Skript Wechselrichter Leistung anpassen ausführen
description: ""
trigger:
  - platform: time_pattern
    seconds: /5
condition: []
action:
  - service: script.turn_on
    target:
      entity_id: script.anpassung_wechselrichter_leistung
mode: single
