alias: Anpassung Wechselrichter Leistung starten
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - service: script.turn_on
    target:
      entity_id: script.anpassung_wechselrichter_leistung
mode: single
